- name: Adicionar a chave do repositório do Unity Hub
  ansible.builtin.get_url:
    url: https://hub.unity3d.com/linux/keys/public
    dest: /etc/apt/keyrings/unityhub.asc
    mode: '0644'
    owner: root
    group: root
  when: ansible_os_family == 'Debian'

- name: Adicionar repositório AnyDesk
  ansible.builtin.copy:
    content: "deb [arch=amd64 signed-by=/etc/apt/keyrings/unityhub.asc] https://hub.unity3d.com/linux/repos/deb stable main"
    dest: /etc/apt/sources.list.d/unityhub.list
    owner: root
    group: root
    mode: '0644'
  when: ansible_os_family == 'Debian'

- name: Instala AnyDesk
  ansible.builtin.apt:
    pkg:
      - unityhub
    update_cache: true
  when: ansible_os_family == 'Debian'
