- name: Instalar o cups-pdf
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - cups
      - printer-driver-cups-pdf
  when: ( ansible_os_family == 'Debian' and cups_server_install == 1)

- name: Para o serviço cups
  ansible.builtin.service:
    name: cups
    state: stopped
  when: ( ansible_os_family == 'Debian' and cups_server_install == 1)

- name: Copia o arquivos de configuração
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: '/etc/cups/{{ item }}'
    owner: root
    group: root
    mode: '0644'
  loop:
    - cups-browsed.conf
    - cupsd.conf
  when: ( ansible_os_family == 'Debian' and  cups_server_install == 1 )
  notify: Restart_cups-browsed

- name: Cria diretório /usr/share/cups/model/argox/ - Linux
  ansible.builtin.file:
    path: /usr/share/cups/model/argox/
    state: directory
    owner: root
    group: root
    mode: '0755'
  when: ( ansible_os_family == 'Debian' and  cups_server_install == 1 and cups_server_argox == 1 )

- name: Copia os arquivos ppd Argox - Linux Debian
  ansible.builtin.copy:
    src: ppd/argox_OS-214_plus_ppla.ppd
    dest: /usr/share/cups/model/argox/
    owner: root
    group: root
    mode: '0644'
  when: ( ansible_os_family == 'Debian' and  cups_server_install == 1 and cups_server_argox == 1 )

- name: Copia os arquivos ppd Argox para /etc/cups/ppd/  - Linux Debian
  ansible.builtin.copy:
    src: ppd/argox_OS-214_plus_ppla.ppd
    dest: /etc/cups/ppd/Argox.ppd
    owner: root
    group: lp
    mode: '0640'
  when: ( ansible_os_family == 'Debian' and  cups_server_install == 1 and cups_server_argox == 1 )

- name: Copia o arquivo rastertoargox - Linux Debian
  ansible.builtin.copy:
    src: rastertoargox
    dest: /usr/lib/cups/filter/rastertoargox
    owner: root
    group: root
    mode: '0755'
  when: ( ansible_os_family == 'Debian' and  cups_server_install == 1 and cups_server_argox == 1 )

- name: Cria diretório /usr/share/cups/model/zebra/ - Linux
  ansible.builtin.file:
    path: /usr/share/cups/model/zebra/
    state: directory
    owner: root
    group: root
    mode: '0755'
  when: ( ansible_os_family == 'Debian' and  cups_server_install == 1 and cups_server_zebra == 1 )

- name: Copia os arquivos ppd Zebra - Linux Debian
  ansible.builtin.copy:
    src: ppd/ZTC-ZD230-203dpi-ZPL.ppd
    dest: /usr/share/cups/model/zebra/
    owner: root
    group: root
    mode: '0644'
  when: ( ansible_os_family == 'Debian' and  cups_server_install == 1 and cups_server_zebra == 1 )

- name: Copia os arquivos ppd zebra para /etc/cups/ppd/  - Linux Debian
  ansible.builtin.copy:
    src: ppd/ZTC-ZD230-203dpi-ZPL.ppd
    dest: /etc/cups/ppd/Zebra.ppd
    owner: root
    group: lp
    mode: '0640'
  when: ( ansible_os_family == 'Debian' and  cups_server_install == 1 and cups_server_zebra == 1 )

- name: Cria arquivo /etc/cups/printers.conf
  ansible.builtin.copy:
    src: printers.conf
    dest: /etc/cups/printers.conf
    owner: root
    group: lp
    mode: '0600'
  when: ( ansible_os_family == 'Debian' and  cups_server_install == 1)
  notify: Restart_cups

- name: Instala a impressora Argox - Linux
  ansible.builtin.blockinfile:
    path: /etc/cups/printers.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK - Argox"
    content: |
      <Printer Argox>
      UUID urn:uuid:9725d01e-d047-38d5-706e-0b2406ed785c
      Info Argox
      Location Patrimonio
      MakeModel ARGOX OS-214 plus PPLA
      DeviceURI parallel:/dev/usb/lp0
      State Idle
      StateTime 1541683378
      ConfigTime 1541682710
      Type 36932
      Accepting Yes
      Shared No
      JobSheets none none
      QuotaPeriod 0
      PageLimit 0
      KLimit 0
      OpPolicy default
      ErrorPolicy retry-job
      </Printer>
  when: ( ansible_os_family == 'Debian' and  cups_server_install == 1 and cups_server_argox == 1 )

- name: Instala a impressora reprografia_reserva - Linux
  ansible.builtin.blockinfile:
    path: /etc/cups/printers.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK reprografia_reserva "
    content: |
      <Printer reprografia_reserva>
      UUID urn:uuid:aa0cf28d-3e7b-3723-70bf-da3cc8a1df02
      Info Kyocera Taskalfa 5003i
      Location Reprografia
      MakeModel Kyocera TASKalfa 5501i (KPDL)
      DeviceURI ipp://cups/printers/reprografia_reserva
      State Idle
      StateTime 1770919541
      ConfigTime 1740410834
      Type 8433876
      Accepting Yes
      Shared No
      JobSheets none none
      QuotaPeriod 0
      PageLimit 0
      KLimit 0
      OpPolicy default
      ErrorPolicy abort-job
      Option print-color-mode monochrome
      Attribute marker-colors \#000000,none
      Attribute marker-levels 78,-1
      Attribute marker-names TK-6327,Waste Toner Box
      Attribute marker-types toner,waste-toner
      Attribute marker-change-time 1770919541
      </Printer>
  when: ( ansible_os_family == 'Debian' and  cups_server_install == 1 and cups_server_reprografia_reserva == 1 )

- name: Instala a impressora reprografia_principal - Linux
  ansible.builtin.blockinfile:
    path: /etc/cups/printers.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK reprografia_principal"
    content: |
      <DefaultPrinter reprografia_principal>
      UUID urn:uuid:d0430e96-df34-3b84-7ac2-e69ad2abb9f6
      Info Lexmark MX911de
      Location Reprografia
      MakeModel Lexmark MX910 Series
      DeviceURI ipp://cups/printers/reprografia_principal
      State Idle
      Type 8433876
      Accepting Yes
      Shared No
      JobSheets none none
      QuotaPeriod 0
      PageLimit 0
      KLimit 0
      OpPolicy default
      ErrorPolicy abort-job
      Option print-color-mode monochrome
      Attribute marker-colors \#000000,none
      Attribute marker-levels -1,-1
      Attribute marker-names TK-6307,Waste Toner Box
      Attribute marker-types toner,waste-toner
      Attribute marker-change-time 1753094192
      </DefaultPrinter>
  when: ( ansible_os_family == 'Debian' and  cups_server_install == 1 and cups_server_reprografia_principal == 1 )

- name: Instala a impressora ImpCGP - Linux
  ansible.builtin.blockinfile:
    path: /etc/cups/printers.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK ImpCGP"
    content: |
      <Printer ImpCGP>
      UUID urn:uuid:d715e5dc-7178-3e8d-5f44-7012443466bc
      Info Lexmark MX611dhe
      Location CGP
      MakeModel Lexmark MX610 Series
      DeviceURI ipp://cups/printers/ImpCGP
      State Idle
      StateTime 1474292746
      ConfigTime 1496336591
      Type 6
      Accepting Yes
      Shared No
      JobSheets none none
      QuotaPeriod 0
      PageLimit 0
      KLimit 0
      OpPolicy default
      ErrorPolicy abort-job
      </Printer>
  when: ( ansible_os_family == 'Debian' and  cups_server_install == 1 and cups_server_cgp == 1 )

- name: Instala a impressora ImpBiblioteca_USB - Linux
  ansible.builtin.blockinfile:
    path: /etc/cups/printers.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK ImpBiblioteca_USB"
    content: |
      <Printer ImpBiblioteca>
      UUID urn:uuid:fb4156cd-356d-3c05-4a36-205fe33f2293
      Info ImpBiblioteca
      Location Biblioteca
      MakeModel HP LaserJet 1020 Foomatic/foo2zjs-z1 (recommended)
      DeviceURI hp:/usb/HP_LaserJet_1020?serial=FZ04KNA
      State Idle
      StateTime 1542736660
      ConfigTime 1542736640
      Type 8425476
      Accepting Yes
      Shared Yes
      JobSheets none none
      QuotaPeriod 0
      PageLimit 0
      KLimit 0
      OpPolicy default
      AllowUser @sj-sebib
      AllowUser biblioteca
      AllowUser ctic
      ErrorPolicy retry-job
      </Printer>
  when: ( ansible_os_family == 'Debian' and  cups_server_install == 1 and cups_server_biblioteca_usb == 1 )

- name: Instala a impressora ImpDirecao - Linux
  ansible.builtin.blockinfile:
    path: /etc/cups/printers.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK ImpDirecao"
    content: |
      <Printer ImpDirecaoColor>
      UUID urn:uuid:a24181f7-e0c1-3ce6-541d-9cc52ee9f9f2
      Info Lexmark CX725dhe
      Location Direcao
      MakeModel Lexmark CX725 Series
      DeviceURI ipp://cups/printers/ImpDirecaoColor
      State Idle
      StateTime 1474293271
      ConfigTime 1496336591
      Type 6
      Accepting Yes
      Shared No
      JobSheets none none
      QuotaPeriod 0
      PageLimit 0
      KLimit 0
      OpPolicy default
      ErrorPolicy abort-job
      </Printer>
  when: ( ansible_os_family == 'Debian' and  cups_server_install == 1 and cups_server_direcao == 1 )

- name: Instala a impressora ImpFinanceiro - Linux
  ansible.builtin.blockinfile:
    path: /etc/cups/printers.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK ImpFinanceiro"
    content: |
      <Printer ImpFinanceiro>
      UUID urn:uuid:ab4361e0-c24c-3b1e-4307-22d869620253
      Info Lexmark MX611dhe
      Location Financeiro
      MakeModel Lexmark MX610 Series
      DeviceURI ipp://cups/printers/ImpFinanceiro
      State Idle
      StateTime 1474292859
      ConfigTime 1496336591
      Type 6
      Accepting Yes
      Shared No
      JobSheets none none
      QuotaPeriod 0
      PageLimit 0
      KLimit 0
      OpPolicy default
      ErrorPolicy abort-job
      </Printer>
  when: ( ansible_os_family == 'Debian' and  cups_server_install == 1 and cups_server_financeiro == 1 )

- name: Instala a impressora ImpSecretaria - Linux
  ansible.builtin.blockinfile:
    path: /etc/cups/printers.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK ImpSecretaria"
    content: |
      <Printer ImpSecretaria>
      UUID urn:uuid:81f5a635-f301-3630-452f-ed201b33e272
      Info Lexmark MX611dhe
      Location Secretaria
      MakeModel Lexmark MX610 Series
      DeviceURI ipp://cups/printers/ImpSecretaria
      State Idle
      StateTime 1474292916
      ConfigTime 1496336591
      Type 6
      Accepting Yes
      Shared No
      JobSheets none none
      QuotaPeriod 0
      PageLimit 0
      KLimit 0
      OpPolicy default
      ErrorPolicy abort-job
      </Printer>
  when: ( ansible_os_family == 'Debian' and  cups_server_install == 1 and cups_server_secretaria == 1 )

- name: Instala a impressora Almoxarifado Deskjet 6940- Linux
  ansible.builtin.blockinfile:
    path: /etc/cups/printers.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK Almoxarifado"
    content: |
      <Printer Deskjet_6940>
      UUID urn:uuid:281b599f-9aa4-33f1-5de3-abeaaf1bc406
      Info
      Location
      MakeModel HP Deskjet 6940 Series, hpcups 3.16.11
      DeviceURI hp:/usb/Deskjet_6940_series?serial=MY7589R3MN04Q9
      State Idle
      StateTime 1565271802
      ConfigTime 1565271300
      Type 36892
      Accepting Yes
      Shared Yes
      JobSheets none none
      QuotaPeriod 0
      PageLimit 0
      KLimit 0
      OpPolicy default
      ErrorPolicy retry-job
      </Printer>
  when: ( ansible_os_family == 'Debian' and  cups_server_install == 1 and cups_server_almoxarifado_6940 == 1 )

- name: Instala o hplip
  ansible.builtin.apt:
    pkg:
      - hplip
      - hplip-gui
      - printer-driver-hpcups
  when: ( ansible_os_family == 'Debian' and  cups_server_install == 1 and cups_server_almoxarifado_6940 == 1 )

- name: Instala a impressora Almoxarifado Deskjet 3920- Linux
  ansible.builtin.blockinfile:
    path: /etc/cups/printers.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK Almoxarifado"
    content: |
      <Printer HP_Deskjet_3900>
      UUID urn:uuid:ed199bbf-642e-3349-713e-6db761b2a21d
      Info HP Deskjet 3900
      Location
      MakeModel HP Deskjet 3900, hpcups 3.18.12
      DeviceURI hp:/usb/Deskjet_3900?serial=CN65K1P02T04CK
      State Idle
      StateTime 1651001137
      ConfigTime 1651001144
      Type 36892
      Accepting Yes
      Shared No
      JobSheets none none
      QuotaPeriod 0
      PageLimit 0
      KLimit 0
      OpPolicy default
      ErrorPolicy retry-job
      </Printer>
  when: ( ansible_os_family == 'Debian' and  cups_server_install == 1 and cups_server_almoxarifado_3920 == 1 )

- name: Instala o hplip
  ansible.builtin.apt:
    pkg:
      - hplip
      - hplip-gui
      - printer-driver-hpcups
  when: ( ansible_os_family == 'Debian' and  cups_server_install == 1 and cups_server_almoxarifado_3920 == 1 )

- name: Copia os arquivos ppd Almoxarifado Deskjet 6940 - Linux Debian
  ansible.builtin.copy:
    src: ppd/Deskjet_6940.ppd
    dest: /etc/cups/ppd/Deskjet_6940.ppd
    owner: root
    group: root
    mode: '0644'
  when: ( ansible_os_family == 'Debian' and  cups_server_install == 1 and cups_server_almoxarifado_6940 == 1 )

- name: Copia os arquivos ppd Almoxarifado Deskjet 3920 - Linux Debian
  ansible.builtin.copy:
    src: ppd/HP_Deskjet_3900.ppd
    dest: /etc/cups/ppd/HP_Deskjet_3900.ppd
    owner: root
    group: root
    mode: '0644'
  when: ( ansible_os_family == 'Debian' and  cups_server_install == 1 and cups_server_almoxarifado_3920 == 1 )

- name: Instala a impressora ImpBiblio - Linux
  ansible.builtin.blockinfile:
    path: /etc/cups/printers.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK ImpBiblio"
    content: |
      <Printer ImpBiblio>
      UUID urn:uuid:44b57a23-1446-3ea9-4b18-47b2d62c999e
      AuthInfoRequired none
      Info ImpBiblioteca
      DeviceURI ipp://191.36.9.251/printers/ImpBiblioteca
      State Idle
      StateTime 1487873280
      Type 6
      Accepting Yes
      Shared No
      JobSheets none none
      QuotaPeriod 0
      PageLimit 0
      KLimit 0
      AllowUser @sj-sebib
      AllowUser biblioteca
      AllowUser ctic
      OpPolicy default
      ErrorPolicy abort-job
      </Printer>
  when: ( ansible_os_family == 'Debian' and  cups_server_install == 1 and cups_server_biblioteca == 1 )

- name: Instalar o cups-pdf - Debian buster
  ansible.builtin.apt:
    name: printer-driver-cups-pdf
  when: ( ansible_os_family == 'Debian' and cups_server_install == 1 and cups_server_pdf == 1 )

- name: Instala a impressora PDF - Linux
  ansible.builtin.blockinfile:
    path: /etc/cups/printers.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK pdf"
    content: |
      <DefaultPrinter PDF>
      UUID urn:uuid:180416ee-24f1-36dc-4ae6-85ebd679e4ec
      Info PDF
      MakeModel Generic CUPS-PDF Printer (w/ options)
      DeviceURI cups-pdf:/
      State Idle
      StateTime 1727447925
      ConfigTime 1727447924
      Type 8450124
      Accepting Yes
      Shared No
      JobSheets none none
      QuotaPeriod 0
      PageLimit 0
      KLimit 0
      OpPolicy default
      ErrorPolicy retry-job
      Option pdftops-renderer pdftocairo
      </DefaultPrinter>
  when: ( ansible_os_family == 'Debian' and  cups_server_install == 1 and cups_server_pdf == 1 )

- name: Apaga arquivo cups-client
  ansible.builtin.file:
    path: /etc/cups/client.conf
    state: absent
  when: ( ansible_os_family == 'Debian' and  cups_server_install == 1 )
  notify: Restart_cups
