#Linux
- name: Baixando e instalando o BricsCAD - Linux Debian
  apt:
    deb: https://discovirtual.ifsc.edu.br/index.php/s/DXtYX9v7XWJtO5N/download
  when: ansible_os_family == 'Debian'

- name: Copiando arquivo de licen√ßa - Linux Debian
  copy:
    src: BricsCADV19.lic
    dest: /var/bricsys/
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'


#Windows
- name: Baixar o instalador do Bricscad
  win_get_url:
    url: 'https://discovirtual.ifsc.edu.br/remote.php/webdav/SJE/CTIC/BricsCAD-V18.2.20-1-pt_BR(x64).msi'
    dest: 'C:\instaladores\BricsCAD-V18.2.20-1-pt_BR(x64).msi'
    force: no
    url_username: "{{ url_username }}"
    url_password: "{{ url_password }}"
    timeout: 120
  when: ansible_os_family == 'Windows'

- name: Baixar e instalar o BricsCAD - Windows
  win_package:
    path: 'C:\instaladores\BricsCAD-V18.2.20-1-pt_BR(x64).msi'
    arguments: 'BRXLICENSESERVER="dko" SHOWRELEASENOTES=""'
    product_id: '{0A1EBB09-ADAB-4E6B-9185-54D12E8FBE56}'
    state: present
  when: ansible_os_family == 'Windows'

- name: Baixar o instalador do Bricscad Shape
  win_get_url:
    url: 'https://discovirtual.ifsc.edu.br/remote.php/webdav/SJE/CTIC/BricsCAD-Shape-V19.2.06-1-pt_BR(x64).msi'
    dest: 'C:\instaladores\BricsCAD-Shape-V19.2.06-1-pt_BR(x64).msi'
    force: no
    url_username: "{{ url_username }}"
    url_password: "{{ url_password }}"
    timeout: 120
  when: ansible_os_family == 'Windows'

- name: Baixar e instalar o BricsCAD Shape - Windows
  win_package:
    path: 'C:\instaladores\BricsCAD-Shape-V19.2.06-1-pt_BR(x64).msi'
    product_id: '{05FF4C9D-E628-4F30-99CC-C704F5CB21C0}'
    state: present
  when: ansible_os_family == 'Windows'
