- name: Apagando gradle anterior
  ansible.builtin.file:
    state: absent
    path: '{{ item }}'
  loop:
    - /opt/gradle/gradle-8.2.1
    - /opt/gradle/gradle-8.5
    - /opt/gradle/gradle-8.10
    - /opt/gradle/gradle-8.14.3
  when: (ansible_os_family == 'Debian')

- name: Criando pasta gradle
  ansible.builtin.file:
    state: directory
    path: /opt/gradle
    owner: root
    group: root
    mode: '0755'
  when: (ansible_os_family == 'Debian')

- name: Baixando e extraindo gradle
  ansible.builtin.unarchive:
    src: https://services.gradle.org/distributions/gradle-9.2.1-all.zip
    dest: /opt/gradle
    creates: /opt/gradle/gradle-9.2.1
    remote_src: true
    owner: root
    group: root
  when: ansible_os_family == 'Debian'

- name: Create a symbolic link
  ansible.builtin.file:
    src: /opt/gradle/gradle-9.2.1/bin/gradle
    dest: /usr/bin/gradle
    state: link
  when: ansible_os_family == 'Debian'
