---
#Linux

- name: Desinstala o Pepperflash - Linux
  apt: name=browser-plugin-freshplayer-pepperflash state=absent purge=yes
  when: ansible_os_family == 'Debian'

- name: Criando a pasta /usr/lib/flash-player - Linux Debian
  file:
    path: /usr/lib/flash-player/
    state: directory
    mode: 0755
    owner: root
    group: root
  when: ansible_os_family == 'Debian'

- name: Extraindo o Flash Player NPAPI - Linux Debian
  unarchive:
    src: flash_player_npapi_linux.x86_64.tar.gz
    dest: /usr/lib/flash-player/
    creates: /usr/lib/flash-player/libflashplayer.so
    owner: root
    group: root
    mode: 0755
  when: ansible_os_family == 'Debian'

- name: Criando o link do Flash Player no firefox - Linux Debian
  file:
    src: /usr/lib/flash-player/libflashplayer.so
    dest: /usr/lib/mozilla/plugins/libflashplayer.so
    state: link
  when: ansible_os_family == 'Debian'

- name: Criando o link do menu de propriedades do Flash Player - Linux Debian
  file:
    src: /usr/lib/flash-player/usr/bin/flash-player-properties 
    dest: /usr/bin/flash-player-properties
    state: link
  when: ansible_os_family == 'Debian'

- name: Criando o arquivo flash-player-properties.desktop - Linux Debian
  copy:
    src: flash-player-properties.desktop
    dest: /usr/share/applications/flash-player-properties.desktop
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'
